### ISSUE TITLE
rising/falling block enhancements

### ISSUE THREAD

**Issue by conormackeigan** [korkesh/Dream-Catchers#190]
-sometimes does not continue moving downward after hunter moves out of the way
-collision stopping sometimes causes the next state switch rise/fall to not trigger
-speed seems mostly linear (?), but some weird behaviour surrounding movement speed when stopped by collision with hunter then starts moving again
-might feel better to make movement a bit less linear? might be jarring but a slight smoothening relative to how far it is from the target point might feel less clunky

all just suggestions, if anyone disagrees feel free to close.

**Comment by korkesh** [comment]
Made some adjustments to handling collision; tough to alter speed without rework; out of scope
