### ISSUE TITLE
taking damage in air freezes y position

### ISSUE THREAD

**Issue by conormackeigan** [korkesh/Dream-Catchers#192]
y position is maintained until damage animation finishes

**Comment by korkesh** [comment]
I took a look into this, the problem code happens in the damage state in the player machine. It works fine if the player is grounded. The player is simply slowed down to a stop. 

When in the air, the current code doesn't account for slowing down in the vertical direction and just zeros out any vertical movement. I am wondering if there is a way to continue applying the fall movement (if it exists) on the character while the damage state is occurring, I'm just not familiar enough with the fall code to pick out what I need.

**Comment by conormackeigan** [comment]
I can probably easily add that, but it might look weird falling directly inside the enemy + might get stuck in a damage loop. will try to add some forward knockback to circumvent.

**Comment by conormackeigan** [comment]
addressed this issue but still have to deal with #229
