### ISSUE TITLE
player has to restep on target to get cannonball to refire

### ISSUE THREAD

**Issue by conormackeigan** [korkesh/Dream-Catchers#193]
if switch is down when a ball despawns the next should fire either immediately or on a short timer

**Comment by korkesh** [comment]
An addendum to this, a ball should respawn every time the switch is pushed, even if a ball currently exists from a previous push.

**Comment by Eikoss** [comment]
should be good

**Comment by conormackeigan** [comment]
still happening in final build. was it not merged in?
