### ISSUE TITLE
Jack In the Box Fixes

### ISSUE THREAD

**Issue by korkesh** [korkesh/Dream-Catchers#198]
I put the new jack in the box prefabs into level 1, the following issues pop up
- I can push the jack in the boxes 
- Only the first jack in the box actually exits his box, the others only stay inside their box; open animation never plays
- The first jumping box I encounter just kills itself

**Comment by korkesh** [comment]
Nevermind I don't know how prefabs work. Derp.

The only remaining issue is you can still push them around
(Reassigning appropriate bug level)

**Comment by conormackeigan** [comment]
If you stand on a dream box, jump then switch to nightmare, you land on his head. when he throws a bomb it instantly blows up killing him, hunter does not seem to take damage either.

**Comment by conormackeigan** [comment]
after testing on the merge build, it seems as if during your encounter with the first jack in the box, one of the two in the next section was throwing balls that were landing inside the room. small problem but worth fixing if it's not too time consuming.

**Comment by conormackeigan** [comment]
just managed to get a ball grounded somehow by jumping on it. it started rolling around a bit and still hasn't despawned, hunter's been standing on top of it for a few minutes now

**Comment by korkesh** [comment]
Fixed in next merge, reopen if issues persist
