### ISSUE TITLE
You can set off the most recent checkpoint multiple times

### ISSUE THREAD

**Issue by korkesh** [korkesh/Dream-Catchers#216]
- Once a checkpoint is flagged as current don't repeat the "checkpoint reached" message or sound

**Comment by Eikoss** [comment]
should be fixed... unless they also dont want it when the scene reloads

**Comment by conormackeigan** [comment]
text shouldn't appear on load, but getting rid of the multiple gets is the biggest thing

**Comment by Eikoss** [comment]
wont fix rest
