### ISSUE TITLE
Reverse lockout doors

### ISSUE THREAD

**Issue by conormackeigan** [korkesh/Dream-Catchers#227]
Doors should ideally be opened/closed in a manner that you never encounter one while backtracking, and as of right now whenever the player tries to loop around and stopped by a door, they see the back end of it and it looks like a large block.

**Comment by conormackeigan** [comment]
actually just making it a double sided door is probably easier and looks good

**Comment by korkesh** [comment]
Will require art asset update, out of scope at this time.
