### ISSUE TITLE
controller bugs out and lifts/falls on alternating frames at manip room entrance

### ISSUE THREAD

**Issue by conormackeigan** [korkesh/Dream-Catchers#228]
After jumping up the two wooden boxes leading into the manipulation power get room, if you run straight at the small ledge made up of the floors surrounding the wooden boxes, hunter's transform bugs out really hard. Didn't occur before most recent merge afaik, can't find anything in the scene that would be causing it.  Doesn't even seem to happen on the right side either strangely.

**Comment by korkesh** [comment]
I saw this as well but wasnt getting it in a proper build.

**Comment by conormackeigan** [comment]
lowering the box by a few pixels doesn't affect jump metrics, looks the same, and gets rid of the jitter in editor mode so left it in anyway.
