### ISSUE TITLE
Player can stand on trigger boxes for some reason

### ISSUE THREAD

**Issue by JesiMcMulkin** [korkesh/Dream-Catchers#56]

**Comment by korkesh** [comment]
I don't understand what this bug means

**Comment by JesiMcMulkin** [comment]
Sometimes when a collider is set to a trigger, the player still stands on it instead of falling through it like he should. Not every time though, maybe half the time

**Comment by korkesh** [comment]
Few ways to handle this, will have to discuss best approach.
